version: "3.8"
services:
  frontend:
    build:
      context: ./streamlit-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit-frontend:/app
  backend:
    build:
      context: ./fastapi-backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-backend:/app
